#B script_message bookmarker-menu
#b script_message bookmarker-quick-save
#ctrl+b script_message bookmarker-quick-load

# --- MPV Bookmark List Script Keybinds ---
# Save bookmark
#b script-binding bookmarks-list/save-bookmark

# Delete selected bookmark (when in list)
#alt+d script-binding bookmarks-list/delete-bookmark

# Edit bookmark name (when in list)
#alt+e script-binding bookmarks-list/edit-bookmark-name

# Show bookmarks list
#b b script-binding bookmarks-list/load-list

n       script-binding chapters/add_chapter
ctrl+r  script-binding chapters/remove_chapter
ctrl+i  script-binding chapters/edit_chapter
N       script-binding chapters/write_chapters
ctrl+b  script-binding chapters/write_xml
B       script-binding chapters/write_txt
ctrl+,  script-binding chapters/bake_chapters
K       script-binding chapters/mkvpropedit


# seek-to.lua
# =============
t script-message-to seek_to toggle-seeker


# ctrl+x apply-profile benchmark


0 script-message-to file_rating rate-file 0
1 script-message-to file_rating rate-file 1
2 script-message-to file_rating rate-file 2
3 script-message-to file_rating rate-file 3
4 script-message-to file_rating rate-file 4
5 script-message-to file_rating rate-file 5
